"""
schemas/goal.py

Pydantic models control what data enters and exits the API for Goals.
These are NOT database models — they are validation + serialization contracts.
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel


class GoalCreate(BaseModel):
    """Fields required to create a new goal. goal_id is auto-generated by the service."""
    title: str
    description: Optional[str] = None


class GoalUpdate(BaseModel):
    """All fields optional — only send what you want to change."""
    title: Optional[str] = None
    description: Optional[str] = None


class GoalRead(BaseModel):
    """What the API sends back when returning a goal."""
    goal_id: str
    title: str
    description: Optional[str]
    created_at: datetime

    model_config = {"from_attributes": True}  # allows reading from SQLAlchemy objects