"""
schemas/task_chunk.py

Pydantic schemas for TaskChunk API input/output.

Key design decision: urgency is exposed as a human-readable label
(e.g. "Low") to the API consumer. Internally it is stored as 1-5.
The service layer handles the conversion.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, field_validator


# Maps internal integer levels to human labels and back
URGENCY_INT_TO_LABEL = {
    1: "Very High",
    2: "High",
    3: "Medium",
    4: "Low",
    5: "Very Low",
}
URGENCY_LABEL_TO_INT = {v: k for k, v in URGENCY_INT_TO_LABEL.items()}


class StatusHistoryRead(BaseModel):
    """A single status history entry, returned nested inside a TaskChunkRead."""
    id: int
    from_status: Optional[str]
    to_status: str
    trigger: str
    note: Optional[str]
    timestamp: datetime

    model_config = {"from_attributes": True}


class TaskChunkCreate(BaseModel):
    """
    Fields accepted when creating a new task chunk (Section 8.1 of spec).
    chunk_id is auto-generated by the service — not provided by the caller.
    """
    content: str
    time_period: int                            # hours
    time_divergent: Optional[int] = 0
    urgency_label: Optional[str] = "Low"        # human label
    goal_id: Optional[str] = None
    reference_link: Optional[str] = None

    @field_validator("urgency_label")
    @classmethod
    def validate_urgency(cls, v):
        if v not in URGENCY_LABEL_TO_INT:
            raise ValueError(
                f"urgency_label must be one of: {list(URGENCY_LABEL_TO_INT.keys())}"
            )
        return v

    @field_validator("time_period")
    @classmethod
    def validate_time_period(cls, v):
        if v <= 0:
            raise ValueError("time_period must be a positive integer")
        return v


class TaskChunkUpdate(BaseModel):
    """Fields that can be changed after creation."""
    content: Optional[str] = None
    time_period: Optional[int] = None
    time_divergent: Optional[int] = None
    urgency_label: Optional[str] = None
    goal_id: Optional[str] = None
    reference_link: Optional[str] = None
    status: Optional[str] = None

    @field_validator("urgency_label")
    @classmethod
    def validate_urgency(cls, v):
        if v is not None and v not in URGENCY_LABEL_TO_INT:
            raise ValueError(
                f"urgency_label must be one of: {list(URGENCY_LABEL_TO_INT.keys())}"
            )
        return v


class TaskChunkAssign(BaseModel):
    """Fields required when assigning a task chunk (Section 8.2 of spec)."""
    assigned_date: datetime
    start_time: str                             # "09:00"
    note: Optional[str] = None


class TaskChunkRead(BaseModel):
    """Full task chunk as returned by the API."""
    chunk_id: str
    content: str
    time_period: int
    time_divergent: int
    urgency_label: str                          # converted from urgency_level
    urgency_level: int                          # included for internal use
    status: str
    goal_id: Optional[str]
    reference_link: Optional[str]
    created_at: datetime
    updated_at: datetime
    assigned_date: Optional[datetime]
    start_time: Optional[str]
    calendar_event_id: Optional[str]
    status_history: List[StatusHistoryRead] = []

    model_config = {"from_attributes": True}


class DashboardRead(BaseModel):
    """System-wide counters (Section 6 of spec)."""
    waiting: int
    in_progress: int
    completed: int
    failed: int
    breached: int
    avg_waiting_hours: Optional[float]